### ISSUE TITLE
Bump `aeson` and `quickcheck-classes`

### ISSUE THREAD

**Issue by taktoa** [andrewthad/disjoint-containers#8]
This package is not compatible with `quickcheck-classes == 0.4.14.1`, and the bound on `aeson < 1.3` is too tight (it can build with `aeson == 1.3.1.1`, though I don't know if the tests pass because of the `quickcheck-classes` breakage). Here's the compiler output when building the tests with `quickcheck-classes == 0.4.14.1`:

```
these derivations will be built:
  /nix/store/arrvmc8yh968px6nwrr4hc0raw5binj0-disjoint-containers-0.2.3.drv
building '/nix/store/arrvmc8yh968px6nwrr4hc0raw5binj0-disjoint-containers-0.2.3.drv'...
builder for '/nix/store/arrvmc8yh968px6nwrr4hc0raw5binj0-disjoint-containers-0.2.3.drv' failed with exit code 1; last 10 log lines:
  ignoring (possibly broken) abi-depends field for packages
  Preprocessing test suite 'test' for disjoint-containers-0.2.3..
  Building test suite 'test' for disjoint-containers-0.2.3..
  [1 of 1] Compiling Main             ( test/Spec.hs, dist/build/test/test-tmp/Main.o )
  
  test/Spec.hs:12:33: error:
      Module ‘Test.QuickCheck.Classes’ does not export ‘jsonProps’
     |
  12 | import Test.QuickCheck.Classes (jsonProps)
     |                                 ^^^^^^^^^
error: build of '/nix/store/arrvmc8yh968px6nwrr4hc0raw5binj0-disjoint-containers-0.2.3.drv' failed
```

**Comment by chessai** [comment]
This is now done
